### ISSUE TITLE
Outdated package on pub.dev

### ISSUE THREAD

**Issue by ymauray** [jeffrey0606/flutter_to_debian#15]
The package on pub.dev - which gets activated with `dart pub global activate flutter_to_debian` - is not the latest version:
- it doesn't understand the `flutter_app, nonInteractive` flag, and doesn't allow maintener's scripts to be added.

For whoever stumbles upon the same problem, activate the `github` version with : 
```bash
dart pub global activate https://github.com/jeffrey0606/flutter_to_debian.git --source git 
```

**Comment by bZichett** [comment]
I inevitably had a suspicion this is what was going on and checked the issues, and wham.

**Comment by jeffrey0606** [comment]
Sorry about that 😅 @bZichett . I'm not using a laptop running Linux at the moment, so no way to test and publish a new version on the pub.dev.
But will be installing Ubuntu on my second laptop soon.

**Comment by bZichett** [comment]
> Sorry about that 😅 @bZichett . I'm not using a laptop running Linux at the moment, so no way to test and publish a new version on the pub.dev. But will be installing Ubuntu on my second laptop soon.

Firstly, please do not apologize! This package is excellent and I am most appreciate you decided to share it 🙏.  I can't stand snap / snap store.  So, thank you, Jeff.  

Cross platform dev can be a nasty animal.  I am gaining first hand experience of this.  Inevitably may need to buy a mac to build a flutter macosx app after trying numerous (primarily undocumented) workarounds including compiling and installing an incomplete virtual macosx using "darling" 😳.  

Apparently, the same for windows - but I have a windows installation at least.

**Comment by jeffrey0606** [comment]
Man! please just forget about all those macos virtual machine stuffs and BUY a macbook 😂. I have been there(tyring to run macos in a virtual machine) and it is not a good experience 🥲.

**Comment by Ranger-NF** [comment]
> For whoever stumbles upon the same problem, activate the github version with :
>   dart pub global activate https://github.com/jeffrey0606/flutter_to_debian.git --source git 

I tried this but it showed me an error, Am I doing something wrong? hmm..

```
checking for debian 📦 in root project...Unhandled exception:
type 'YamlList' is not a subtype of type 'String?'
#0      new FlutterToDebian.fromYaml (package:flutter_to_debian/flutter_to_debian.dart:56:28)
#1      Vars.parseDebianYaml (package:flutter_to_debian/vars.dart:26:32)
<asynchronous suspension>
#2      main (file:///home/fahad/.pub-cache/git/flutter_to_debian-eab7d3b7a4bc4d2d124844dc4fd0f68efca2a1a7/bin/flutter_to_debian.dart:35:29)
<asynchronous suspension>```

**Comment by Gustl22** [comment]
@jeffrey0606 would you mind doing a `flutter release`? I already bumped the version in pubspec to 2.0.0. Also you can add a link to the github repo to the [package site](https://pub.dev/packages/flutter_to_debian).

**Comment by Gustl22** [comment]
Release `2.0.2` is out: https://pub.dev/packages/flutter_to_debian
