### ISSUE TITLE
How to pack dependent packages to .deb file

### ISSUE THREAD

**Issue by SteveCruise** [jeffrey0606/flutter_to_debian#2]
My app uses sqlite and need install this. How to pack it into .deb file.
```
sudo apt-get -y install libsqlite3-0 libsqlite3-dev
```

**Comment by jeffrey0606** [comment]
Updated the read me with info about the [Depend](https://github.com/jeffrey0606/flutter_to_debian#depends) attribute in debian.yaml. I think it will help resolve this issue


If your issue is solved please close this issue

**Comment by SteveCruise** [comment]
Fixed. Thank you!
