### ISSUE TITLE
Adding another Exec property to .desktop file even if previously specified 

### ISSUE THREAD

**Issue by jakub-stefaniak** [jeffrey0606/flutter_to_debian#7]
First of all, thanks for this package. It's very useful.

One thing I noticed is adding Exec property without checking if it already exists in .desktop file. 
It would be better to check if desktop file has Exec or TryExec property before adding it. 
In my case I wanted to provide that by myself because I need it with %u at the end.

**Comment by jeffrey0606** [comment]
Hi @jakub-stefaniak happy to hear the package helps you 🤗.

Please can you provide more context on your use case (like why will you like add "%u")?

So that we can maybe try and make more generic because I fear adding an Exec property might break the package current functioning.

**Comment by jakub-stefaniak** [comment]
I wanted to provide %u at the end of the Exec property, so I can run the app with arguments. It's useful when you're handling custom url schemes. I pass the url called from browser as a parameter to flutter app

**Comment by jakub-stefaniak** [comment]
Here's specification what field codes can be passed with exec key
https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html

**Comment by jeffrey0606** [comment]
> I wanted to provide %u at the end of the Exec property, so I can run the app with arguments. It's useful when you're handling custom url schemes. I pass the url called from browser as a parameter to flutter app

Wow this is interesting 😲. 
Please can I have a demo of it in action when you are done with your implementation?

**Comment by jakub-stefaniak** [comment]
Actually, I can't show it in the project that I am currently working on, but after work I can show you simple example of it in action :)

**Comment by jeffrey0606** [comment]
Yep sound good thanks 🙂

**Comment by jeffrey0606** [comment]
Please I will also want you to update the Readme per your changes if you have the time.

**Comment by jakub-stefaniak** [comment]
Sure, will do
