### ISSUE TITLE
[Ubuntu] flutter_to_debian: command not found

### ISSUE THREAD

**Issue by alihassan143test** [jeffrey0606/flutter_to_debian#9]

**Comment by dmitry-engineer** [comment]
The same thing

**Comment by dmitry-engineer** [comment]
Maybe it will help someone. Add the following line in your .bashrc file:
`export PATH="$PATH":"$HOME/.pub-cache/bin"`

**Comment by Gustl22** [comment]
Or just use `dart pub global run flutter_release` :D

**Comment by Gustl22** [comment]
Closing as not directly related to flutter_to_debian
